### ISSUE TITLE
Improves error handling

### ISSUE THREAD

**Issue by kenorb** [FX31337/MQL-Compile-Action#25]
The following build didn't fail:
![image](https://user-images.githubusercontent.com/266306/103311453-52907e00-4a12-11eb-9655-eb0a175cfe55.png)

**Comment by kenorb** [comment]
Same in build [2048377310](https://github.com/EA31337/EA31337-classes/runs/2048377310?check_suite_focus=true#step:3:12868):

```
Warnings/errors occurred. Returning exit code 1.
(node:3376) UnhandledPromiseRejectionWarning: Error: Parameter token or opts.auth is required
    at Object.getAuthString (D:\a\_actions\fx31337\mql-compile-action\master\dist\index.js:932:17)
    at Object.getOctokitOptions (D:\a\_actions\fx31337\mql-compile-action\master\dist\index.js:14407:28)
    at Object.getOctokit (D:\a\_actions\fx31337\mql-compile-action\master\dist\index.js:13939:43)
    at module.exports (D:\a\_actions\fx31337\mql-compile-action\master\dist\index.js:13872:32)
    at D:\a\_actions\fx31337\mql-compile-action\master\dist\index.js:732:25
    at extractFiles (D:\a\_actions\fx31337\mql-compile-action\master\dist\index.js:24649:37)
    at D:\a\_actions\fx31337\mql-compile-action\master\dist\index.js:24657:13
    at WriteStream.<anonymous> (D:\a\_actions\fx31337\mql-compile-action\master\dist\index.js:24624:35)
    at WriteStream.emit (events.js:215:7)
    at finishMaybe (_stream_writable.js:656:14)
(node:3376) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:3376) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by kenorb** [comment]
```
Unzipping "metaeditor5.zip"...
Renaming MetaTrader's folder from "../MetaTrader 5" into "../MetaTrader"...
Cannot rename MetaTrader's folder!
(node:600) UnhandledPromiseRejectionWarning: Error: EPERM: operation not permitted, rename '../MetaTrader 5' -> '../MetaTrader'
    at Object.renameSync (fs.js:643:3)
    at D:\a\_actions\fx31337\mql-compile-action\master\dist\index.js:621:22
    at extractFiles (D:\a\_actions\fx31337\mql-compile-action\master\dist\index.js:24649:37)
    at D:\a\_actions\fx31337\mql-compile-action\master\dist\index.js:24657:13
    at WriteStream.<anonymous> (D:\a\_actions\fx31337\mql-compile-action\master\dist\index.js:24624:35)
    at WriteStream.emit (events.js:215:7)
    at finishMaybe (_stream_writable.js:656:14)
    at _stream_writable.js:634:5
    at WriteStream._final (internal/fs/streams.js:285:3)
    at callFinal (_stream_writable.js:627:10)
(node:600) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:600) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by kenorb** [comment]
```
Unzipping "metaeditor5.zip"...
Renaming MetaTrader's folder from "../MetaTrader 5" into "../MetaTrader"...
Executing: "../MetaTrader/terminal64.exe" /portable /config:tester.ini
Executing: "../MetaTrader/metaeditor64.exe" /portable /inc:"." /compile:"Indicators/SuperTrend.mq4" /log:"mql.log" 
(node:4584) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'mql.log'
    at Object.openSync (fs.js:440:3)
    at Object.readFileSync (fs.js:342:35)
    at D:\a\_actions\fx31337\mql-compile-action\master\dist\index.js:684:20
    at extractFiles (D:\a\_actions\fx31337\mql-compile-action\master\dist\index.js:24649:37)
    at D:\a\_actions\fx31337\mql-compile-action\master\dist\index.js:24657:13
    at WriteStream.<anonymous> (D:\a\_actions\fx31337\mql-compile-action\master\dist\index.js:24624:35)
    at WriteStream.emit (events.js:215:7)
    at finishMaybe (_stream_writable.js:656:14)
    at _stream_writable.js:634:5
    at WriteStream._final (internal/fs/streams.js:285:3)
(node:4584) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4584) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by kenorb** [comment]
Fixed in GH-34.
